### ISSUE TITLE
Wrong version of package.json 0.1.5, 0.1.4

### ISSUE THREAD

**Issue by favoyang** [mzaks/FlexBuffersUnity#1]
package.json version is still 0.1.3 for 
- https://github.com/mzaks/FlexBuffersUnity/releases/tag/0.1.5
- https://github.com/mzaks/FlexBuffersUnity/releases/tag/0.1.4

Please consider to bump version 0.1.5, then re-tag it. Or bump version to 0.1.6 and release a new version.

BTW, GitHub releases can be created with [an automatic approach](https://medium.com/openupm/how-to-maintain-upm-package-part-2-f352fbf5f87c).

**Comment by mzaks** [comment]
Thank you for pointing it out and sharing the link for automatic approach.
I currently just released version 0.1.6 with correct version in package.json, but for the long run I will definitely have a look into automation.
